name = "prismatic"
author = "lizard_thief_fighter"
version = "v0.0g"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ca147ebf3c6c17d9d882ba90f68d04d0d298195a5117b6968561b4fa8baa0197"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
