name = "prismatic"
author = "lizard_thief_fighter"
version = "v0.1a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a35d046a8ffce715d99cae4ce2a5ebaeeec7e4049b490a68cecfc79b46ee5958"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
